This notebook is conducted based on :
* the book [Python Data Science Handbook](http://shop.oreilly.com/product/0636920034919.do) by Jake VanderPlas.
* Python Numpy Tutorial, available at https://cs231n.github.io/python-numpy-tutorial/#array-math
* NumPy Crash Course 2020 - Complete Tutorial, available at https://www.python-engineer.com/posts/numpy-crash-course/

# The Basics of NumPy Arrays

Data manipulation in Python is nearly synonymous with NumPy array manipulation: even newer tools like Pandas ([Chapter 3](03.00-Introduction-to-Pandas.ipynb)) are built around the NumPy array.
This section will present several examples of using NumPy array manipulation to access data and subarrays, and to split, reshape, and join the arrays.
While the types of operations shown here may seem a bit dry and pedantic, they comprise the building blocks of many other examples used throughout the book.
Get to know them well!

We'll cover a few categories of basic array manipulations here:

- *Creating arrays*: Exploring various utilities for creating NumPy arrays
- *Attributes of arrays*: Determining the size, shape, memory consumption, and data types of arrays
- *Indexing of arrays*: Getting and setting the value of individual array elements
- *Slicing of arrays*: Getting and setting smaller subarrays within a larger array
- *Reshaping of arrays*: Changing the shape of a given array
- *Joining and splitting of arrays*: Combining multiple arrays into one, and splitting one array into many
- *Broadcasting arrays*

## What is NumPy?

`numpy` (numerical Python) is a Python library that supports large, multi-dimentional arrays and matrices. `numpy` provides a large collection of high-level mathematical functions to operate on these arrays.

NumPy arrays are of type `nd-array` standing for *n-dimensional array*.

In [3]:
%pip install numpy

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.4/5.4 MB 426.6 kB/s  0:00:12a 0:00:010:00:01:09

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [4]:
import numpy as np
np.__version__

'2.5.2'

In [5]:
arr = np.array([1, 2, 3, 4])
#arr
#print(arr, '\n')
#print(type(arr), '\n')
#print(type(arr[0]), '\n')

## Creating NumPy Arrays

The `numpy` library has many utilities for creating arrays. 

In [9]:
# create a 1d-array filled with evenly spaced integers
#d1_data = np.arange(10)       # start=0, stop=10 (exclusive)
d1_data = np.arange(3, 7)    # start=3, stop=7 (exclusive)
d1_data

array([3, 4, 5, 6])

In [8]:
# parameters are nd-array size 
#d1_data = np.random.rand(4)
d1_data = np.random.rand(3,4)
#d1_data = np.random.rand(2,3,4)
d1_data

array([[0.06038535, 0.93887884, 0.34432845, 0.97532486],
       [0.88828164, 0.41182896, 0.43664373, 0.04928923],
       [0.84008729, 0.05775924, 0.56208487, 0.67414173]])

In [10]:
#d1_data = np.random.randint(10, size=(4))      # low = 10, high = None; so, we get int within the range [0, 10) 
#d1_data = np.random.randint(10, size=(3,4))
d1_data = np.random.randint(10, size=(2,3,4))
d1_data

array([[[2, 6, 9, 6],
        [5, 4, 4, 5],
        [3, 3, 7, 5]],

       [[7, 0, 9, 9],
        [8, 1, 6, 5],
        [9, 6, 1, 0]]])

In [11]:
# 'ones' create an array filled with ones
#d1_ones = np.ones(4)
d1_ones = np.ones((3,4), dtype=int)
#d1_ones = np.ones((2,3,4))
d1_ones


array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [12]:
# 'zeros' create an array filled with zeroes
d1_zeros = np.zeros(4)
#d1_zeros = np.zeros((3,4))
#d1_zeros = np.zeros((2,3,4))
d1_zeros

array([0., 0., 0., 0.])

In [13]:
# 'eye' create an identity matrix 
d1_eyes  = np.eye(4)   
d1_eyes

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## NumPy Array Attributes

First let's discuss some useful array attributes.
We'll start by defining three random arrays, a one-dimensional, two-dimensional, and three-dimensional array.
We'll use NumPy's random number generator, which we will *seed* with a set value in order to ensure that the same random arrays are generated each time this code is run:

In [16]:
import numpy as np
np.random.seed(0)  # seed for reproducibility

x1 = np.random.randint(10, size=4)          # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))     # Two-dimensional array
x3 = np.random.randint(10, size=(2, 3, 4))  # Three-dimensional array

x1 = np.arange(4)                            # One-dimensional array
x2 = np.arange(12).reshape(3,4)              # Two-dimensional array
x3 = np.arange(24).reshape(2,3,4)             # Three-dimensional array

print(repr(x1), '\n')
print(repr(x2), '\n')
print(repr(x3), '\n')

array([0, 1, 2, 3]) 

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]]) 

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]]) 



![Numpy_Array_3d](https://drive.google.com/uc?export=view&id=1RvXxrO8N7hOfTUCElMxI4DY26K05dcWM)

Each array has attributes ``ndim`` (the number of dimensions), ``shape`` (the size of each dimension), and ``size`` (the total number of elements in the array):

In [ ]:
x3
#print("x3 ndim: ", x3.ndim)
#print("x3 shape:", x3.shape)
#print("x3 size: ", x3.size)

Another useful attribute is the `dtype` (data type object) specifying the data type information of the array.

The dtypes are available as `np.bool_`, `np.float32`, `np.int64`, etc.


In [ ]:
print(x3, '\n')
print("dtype:", x3.dtype)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]] 

dtype: int64


Other attributes include ``itemsize``, which lists the size (in bytes) of each array element, and ``nbytes``, which lists the total size (in bytes) of the array:

In [ ]:
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

In general, we expect that ``nbytes`` is equal to ``itemsize`` times ``size``.

## Array Indexing: Accessing Single Elements

If you are familiar with Python's standard list indexing, indexing in NumPy will feel quite familiar.
In a one-dimensional array, the $i^{th}$ value (counting from zero) can be accessed by specifying the desired index in square brackets, just as with Python lists:

In [ ]:
x1 = np.random.randint(10, size=4) 
x1

array([7, 9, 3, 5])

In [ ]:
x1[0]

In [ ]:
x1[3]

To index from the end of the array, you can use negative indices:

In [ ]:
x1[-1]

In [ ]:
x1[-2]

In a multi-dimensional array, items can be accessed using a comma-separated tuple of indices:

In [ ]:
x2 = np.random.randint(10, size=(3, 4))
x2

array([[2, 4, 7, 6],
       [8, 8, 1, 6],
       [7, 7, 8, 1]])

In [ ]:
x2[0, 0]

In [ ]:
x2[2, 0]

In [ ]:
x2[2, -1]

Values can also be modified using any of the above index notation:

In [ ]:
x2[0, 0] = 12
x2

Keep in mind that, unlike Python lists, NumPy arrays have a fixed type.
This means, for example, that if you attempt to insert a floating-point value to an integer array, the value will be silently truncated. Don't be caught unaware by this behavior!

In [ ]:
print(x1, '\n')
print(x1.dtype, '\n')
x1[0] = 3.14159  # this will be truncated!
print(x1, '\n')

[7 9 3 5] 

int64 

[3 9 3 5] 



## Array Slicing: Accessing Subarrays

Just as we can use square brackets to access individual array elements, we can also use them to access subarrays with the *slice* notation, marked by the colon (``:``) character.
The NumPy slicing syntax follows that of the standard Python list; to access a slice of an array ``x``, use this:
``` python
x[start:stop:step]
```
If any of these are unspecified, they default to the values ``start=0``, ``stop=``*``size of dimension``*, ``step=1``.
We'll take a look at accessing sub-arrays in one dimension and in multiple dimensions.

### One-dimensional subarrays

In [ ]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
x[:5]  # first five elements

array([0, 1, 2, 3, 4])

In [ ]:
x[5:]  # all elements since index 5 till the end

array([5, 6, 7, 8, 9])

In [ ]:
x[4:7]  # middle sub-array

array([4, 5, 6])

In [ ]:
x[::2]  # every other element

array([0, 2, 4, 6, 8])

In [ ]:
x[1::2]  # every other element, starting at index 1

array([1, 3, 5, 7, 9])

A potentially confusing case is when the ``step`` value is negative.
In this case, the defaults for ``start`` and ``stop`` are swapped.
This becomes a convenient way to reverse an array:

In [ ]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
x[::-1]  # all elements, reversed

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [ ]:
x[5::-2]  # reversed every other from index 5

array([5, 3, 1])

### Multi-dimensional subarrays

Multi-dimensional slices work in the same way, with multiple slices separated by commas.

For example:

In [ ]:
x2 = np.arange(12).reshape(3,4)              # Two-dimensional array
x2

In [ ]:
x2[:2, :3]  # two rows, three columns

In [ ]:
x2[:3, ::2]  # all three rows, every other column

Finally, subarray dimensions can even be reversed together:

In [ ]:
x2[::-1, ::-1]

array([[11, 10,  9,  8],
       [ 7,  6,  5,  4],
       [ 3,  2,  1,  0]])

#### Accessing array rows and columns

One commonly needed routine is accessing of single rows or columns of an array.
This can be done by combining indexing and slicing, using an empty slice marked by a single colon (``:``):

In [ ]:
x2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
x2[:, 0]  # first column of x2

array([0, 4, 8])

In [ ]:
x2[0, :]  # first row of x2

array([0, 1, 2, 3])

In the case of row access, the empty slice can be omitted for a more compact syntax:

In [ ]:
x2[0]  # equivalent to x2[0, :]

### Subarrays as no-copy views

One important–and extremely useful–thing to know about array slices is that they return *views* rather than *copies* of the array data.
This is one area in which NumPy array slicing differs from Python list slicing: in lists, slices will be copies.
Consider our two-dimensional array from before:

In [ ]:
x2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

Let's extract a $2 \times 2$ subarray from this:

In [ ]:
x2_sub = x2[:2, :2]
x2_sub

array([[0, 1],
       [4, 5]])

Now if we modify this subarray, we'll see that the original array is changed! Observe:

In [ ]:
x2_sub[0, 0] = 99

print("x2_sub:")
print(repr(x2_sub))
print()
print("x2:")
print(repr(x2))


x2_sub:
array([[99,  1],
       [ 4,  5]])

x2:
array([[99,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])


This default behavior is actually quite useful: it means that when we work with large datasets, we can access and process pieces of these datasets without the need to copy the underlying data buffer.

### Creating copies of arrays

Despite the nice features of array views, it is sometimes useful to instead explicitly copy the data within an array or a subarray. This can be most easily done with the ``copy()`` method:

In [ ]:
x2_sub_copy = x2[:2, :2].copy()
print(repr(x2_sub_copy))

array([[99,  1],
       [ 4,  5]])


If we now modify this subarray, the original array is not touched:

In [ ]:
x2_sub_copy[0, 0] = 42

print("x2_sub_copy:")
print(repr(x2_sub_copy))
print()
print("x2:")
print(repr(x2))

x2_sub_copy:
array([[42,  1],
       [ 4,  5]])

x2:
array([[99,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])


## Array Boolean Indexing: Accessing Element(s) Satisfying Condition 
Using Boolean to select only values satisfying the desired condition.

In [ ]:
# First, create a 2d array of size 6 with the shape (3, 2):
a = np.array([[1,2], [3, 4], [5, 6]])
print("ndim = ", a.ndim)      # 2
print("shape= ", a.shape)     # (3, 2)
print("size = ", a.size)      # 6
print(a)                      # [[1 2]
                              #  [3 4]
                              #  [5 6]]

ndim =  2
shape=  (3, 2)
size =  6
[[1 2]
 [3 4]
 [5 6]]


In [ ]:
# สร้าง boolean indexing
# note! the same shape with True or False for the condition
bool_idx = a > 2
#print(bool_idx)               #  [[False False]
                              #   [True  True]
                              #   [True  True]]

# note: this will be a 1d array!
#print(a[bool_idx]) # [3 4 5 6]

# We can do all of the above in a single concise statement:
#print(a[a > 2])   # [3 4 5 6]

# ทดลองสร้าง boolean index เพื่อเลือกเฉพาะเลขคู่ภายในอาร์เรย์ 
# และทดสอบ boolean index ที่นักศึกษาสร้างขึ้นด้วยการเรียกใช้งาน

In [ ]:
# numpy.where(): return the indices of elements in an input array where the given condition is satisfied.

# Syntax: numpy.where(condition[, x, y])
# 1. If both parameters x and y are specified, the output array contains elements of x where condition is True, and elements from y elsewhere.
#    note: the output array is the same size with modified values
b = np.where(a>2, a, -1)
print(b)                # [[-1 -1]
                        #  [ 3  4]
                        #  [ 5  6]]

# Syntax: numpy.where(condition[, x, y])
# 2. If only condition is given, return the tuple condition.nonzero(), i.e. the indices where condition is True.
b = np.where(a>2)
print(b)   # (array([1, 1, 2, 2]), array([0, 1, 0, 1]))
           # indices where condition is true: (1,0) (1,1) (2,0) (2,1)

In [ ]:
# fancy indexing: 

# 1. access multiple indices at once
a = np.array([10, 19, 30, 41, 50, 61])
b = a[[1,3,5]]
#print(b)                # [19 41 61]

# 2. compute indices where condition is True
even_idx = np.where(a%2==0)
print(even_idx)
even = a[even_idx]
print(even)

## Reshaping of Arrays

Another useful type of operation is reshaping of arrays.
The most flexible way of doing this is with the ``reshape`` method.
For example, if you want to put the numbers 1 through 9 in a $3 \times 3$ grid, you can do the following:

In [ ]:
grid = np.arange(1, 10).reshape((3, 3))
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Note that for this to work, the size of the initial array must match the size of the reshaped array. 
Where possible, the ``reshape`` method will use a no-copy view of the initial array, but with non-contiguous memory buffers this is not always the case.

Another common reshaping pattern is the conversion of a one-dimensional array into a two-dimensional row or column matrix.
This can be done with the ``reshape`` method, or more easily done by making use of the ``newaxis`` keyword within a slice operation:

In [ ]:
# x is a one-dimensional array
x = np.array([1, 2, 3])
print(x)
print("x has # of dimensions = ", x.ndim)
print()

# row vector via reshape
# y is a two-dimensional array with one row, three columns
y = x.reshape((1, 3))
print(y)
print("y has # of dimensions = ", y.ndim)

In [ ]:
# row vector via newaxis
print(x, '\n')
print(x[np.newaxis, :])

In [ ]:
# column vector via reshape
z = x.reshape((3, 1))
print(z)
print("z has # of dimensions = ", z.ndim)

In [ ]:
# column vector via newaxis
x[:, np.newaxis]

We will see this type of transformation often throughout the remainder of the course.

## Operations on Arrays: Baic Math Operations

Basic mathematical functions operate elementwise on arrays, and are available both as operator overloads and as functions in the numpy module:

In [ ]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Elementwise sum; both produce the array
# [[ 6.0  8.0]
#  [10.0 12.0]]
print(x + y)                # use the overloaded operator 
print(np.add(x, y), '\n')         # use the function call

# Elementwise difference; both produce the array
# [[-4.0 -4.0]
#  [-4.0 -4.0]]
print(x - y)
print(np.subtract(x, y), '\n')

# Elementwise product; both produce the array
# [[ 5.0 12.0]
#  [21.0 32.0]]
print(x * y)
print(np.multiply(x, y), '\n')

# Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y), '\n')

# Elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))

### Dot Product and Matrix Multiplication

We use the ``dot`` function to compute inner products of vectors, to multiply a vector by a matrix, and to multiply matrices. ``dot`` is available both as a function in the *numpy* module and as an instance method of array objects:

In [ ]:
import numpy as np

x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9, 10])
w = np.array([11, 12])

# Inner product of vectors; both produce 219
# (9*11) + (10*12) = 99 + 120 = 219
print(v.dot(w))
print(np.dot(v, w))

# Matrix / vector product; both produce the 1d array [29 67]
# เมทริกซ์ x เวคเตอร์ 
print(x.dot(v))
print(np.dot(x, v))

# Matrix / matrix product; both produce the 2d array
# เมทริกซ์ x เมทริกซ์
# [[19 22]
#  [43 50]]
print(x.dot(y))
print(np.dot(x, y))

### Aggregate Sum

Numpy provides many useful functions for performing computations on arrays; one of the most useful is ``sum``:

In [ ]:
import numpy as np

x = np.array([[0,1,2],
              [3,4,5]])

print(np.sum(x))          # Compute sum of all elements; prints "15"
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[3 5 7]"
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[3 12]"

![Numpy_Sum_with_Axis_set](https://drive.google.com/uc?export=view&id=17pKxqbw_ObSl8zAPdR8FF0F4GWlxIBgh)

The same concept can be applied to 3d arrays.

In [ ]:
y = np.arange(0,24).reshape(2, 3, 4)
print(y, '\n')
print(np.sum(y), '\n')    #276           
print(np.sum(y, axis=0), '\n')
print(np.sum(y, axis=1), '\n')
print(np.sum(y, axis=2), '\n')

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]] 

276 

[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]] 

[[12 15 18 21]
 [48 51 54 57]] 

[[ 6 22 38]
 [54 70 86]] 



![Numpy_Array_3d](https://drive.google.com/uc?export=view&id=1RvXxrO8N7hOfTUCElMxI4DY26K05dcWM)


## Array Concatenation and Array Splitting

All of the preceding routines worked on single arrays. It's also possible to combine multiple arrays into one, and to conversely split a single array into multiple arrays. We'll take a look at those operations here.

### Concatenation of arrays

Concatenation, or joining of two arrays in NumPy, is primarily accomplished using the routines ``np.concatenate``, ``np.vstack``, and ``np.hstack``.
``np.concatenate`` takes a tuple or list of arrays as its first argument, as we can see here:

In [ ]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

You can also concatenate more than two arrays at once:

In [ ]:
z = [99, 99, 99]
print(np.concatenate([x, y, z]))

It can also be used for two-dimensional arrays:

In [ ]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])

In [ ]:
# concatenate along the first axis
k = np.concatenate([grid, grid])
k
k.shape

(4, 3)

In [ ]:
# concatenate along the second axis (zero-indexed)
k = np.concatenate([grid, grid], axis=1)
k
k.shape

(2, 6)

For working with arrays of mixed dimensions, it can be clearer to use the ``np.vstack`` (vertical stack) and ``np.hstack`` (horizontal stack) functions:

In [ ]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])

# vertically stack the arrays
np.vstack([x, grid])

In [ ]:
# horizontally stack the arrays
y = np.array([[99],
              [99]])
np.hstack([grid, y])

Similary, ``np.dstack`` will stack arrays along the third axis.

### Splitting Arrays

The opposite of concatenation is splitting, which is implemented by the functions ``np.split``, ``np.hsplit``, and ``np.vsplit``.  For each of these, we can pass a list of indices giving the split points:

Notice that *N* split-points, leads to *N + 1* subarrays.

In [ ]:
import numpy as np
x = [1, 2, 3, 99, 99, 3, 2, 1]
#x1, x2, x3 = np.split(x, [3, 5])
#print(x1, x2, x3)
x1, x2 = np.split(x, [3])
print(x1, x2)



The related functions ``np.hsplit`` and ``np.vsplit`` are similar:

In [ ]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
upper, lower = np.vsplit(grid, [2])
print(upper, '\n')
print(lower)

In [ ]:
left, right = np.hsplit(grid, [2])
print(left, '\n')
print(right)

Similarly, ``np.dsplit`` will split arrays along the third axis.

## Array Broadcasting:

Broadcasting is a powerful mechanism that allows numpy to work with arrays of different shapes when performing arithmetic operations. Frequently we have a smaller array and a larger array, and we want to use the smaller array multiple times to perform some operation on the larger array.

Recall that for arrays of the same size, binary operations are performed on an element-by-element basis:

In [ ]:
import numpy as np
a = np.array([0, 1, 2])
b = np.array([5, 5, 5])
print(repr(a), '\n')
print(repr(b), '\n')
print(repr(a + b))

Broadcasting allows these types of binary operations to be performed on arrays of different sizes.

For example, we can just as easily add a scalar (think of it as a zero-dimensional array) to an array:

In [ ]:
a + 5

We can think of this as an operation that stretches or duplicates the value ``5`` into the array ``[5, 5, 5]``, and adds the results. The advantage of NumPy's broadcasting is that this duplication of values does not actually take place, but it is a useful mental model as we think about broadcasting.

We can similarly extend this to arrays of higher dimension. Observe the result when we add a one-dimensional array to a two-dimensional array:

In [ ]:
M = np.ones((3, 3))
M

In [ ]:
a

In [ ]:
M + a

Here the one-dimensional array ``a`` is stretched, or broadcast across the second dimension in order to match the shape of ``M``.

While these examples are relatively easy to understand, more complicated cases can involve broadcasting of both arrays. Consider the following example:

In [ ]:
a = np.arange(3)
b = np.arange(3).reshape(3,1)

print(a, '\n')
print(b, '\n')

In [ ]:
a + b

Just as before we stretched or broadcasted one value to match the shape of the other, here we've stretched both a and b to match a common shape, and the result is a two-dimensional array. 

The geometry of these examples is visualized in the following figure.

<u>Note</u> the light boxes represent the broadcasted values. Again, this extra memory is not actually allocated in the course of the operation, but it can be useful conceptually to imagine that it is. 

![Broadcasting Visual](https://github.com/jakevdp/PythonDataScienceHandbook/blob/master/notebooks/figures/02.05-broadcasting.png?raw=1)

<u>**Rules of Broadcasting**</u>

Broadcasting in NumPy follows a strict set of rules to determine the interaction between the two arrays:

- Rule 1: If the two arrays differ in their number of dimensions, the shape of the one with fewer dimensions is *padded* with ones on its leading (left) side.
- Rule 2: If the shape of the two arrays does not match in any dimension, the array with shape equal to 1 in that dimension is stretched to match the other shape.
- Rule 3: If in any dimension the sizes disagree and neither is equal to 1, an error is raised.

To make these rules clear, let's consider a few examples in detail.

<u>Broadcasting Example 1</u>:

Let's look at adding a two-dimensional array to a one-dimensional array:

In [ ]:
M = np.ones((2, 3), dtype="int")
a = np.arange(3)
print(M)
print(a)

Let's consider an operation on these two arrays. The shape of the arrays are

- ``M.shape = (2, 3)``
- ``a.shape = (3,)``

We see by rule 1 that the array ``a`` has fewer dimensions, so we pad it on the left with ones:

- ``M.shape -> (2, 3)``
- ``a.shape -> (1, 3)``

By rule 2, we now see that the first dimension disagrees, so we stretch this dimension to match:

- ``M.shape -> (2, 3)``
- ``a.shape -> (2, 3)``

The shapes match, and we see that the final shape will be ``(2, 3)``:

In [ ]:
M + a

<u>Broadcasting Example 2</u>:

Let's take a look at an example where both arrays need to be broadcast:

In [ ]:
a = np.arange(3).reshape((3, 1))
b = np.arange(3)
print(a, '\n')
print(b, '\n')

Again, we'll start by writing out the shape of the arrays:

- ``a.shape = (3, 1)``
- ``b.shape = (3,)``

Rule 1 says we must pad the shape of ``b`` with ones:

- ``a.shape -> (3, 1)``
- ``b.shape -> (1, 3)``

And rule 2 tells us that we upgrade each of these ones to match the corresponding size of the other array:

- ``a.shape -> (3, 3)``
- ``b.shape -> (3, 3)``

Because the result matches, these shapes are compatible. We can see this here:

In [ ]:
a + b

<u>Broadcasting example 3</u>:

Now let's take a look at an example in which the two arrays are not compatible:

In [ ]:
M = np.ones((3, 2))
a = np.arange(3)

This is just a slightly different situation than in the first example: the matrix ``M`` is transposed.
How does this affect the calculation? The shape of the arrays are

- ``M.shape = (3, 2)``
- ``a.shape = (3,)``

Again, rule 1 tells us that we must pad the shape of ``a`` with ones:

- ``M.shape -> (3, 2)``
- ``a.shape -> (1, 3)``

By rule 2, the first dimension of ``a`` is stretched to match that of ``M``:

- ``M.shape -> (3, 2)``
- ``a.shape -> (3, 3)``

Now we hit rule 3–the final shapes do not match, so these two arrays are incompatible, as we can observe by attempting this operation:

In [ ]:
M + a

ValueError: ignored